### ISSUE TITLE
Clicking "Live" button puts the camera in software trigger mode

### ISSUE THREAD

**Issue by omarjamil** [UniExeterRSE/NetClamp#102]
To create ROIs need to do live imaging. The live imaging should put the camera in software trigger mode.

**Comment by felicityguest** [comment]
@omarjamil, I can't see `triggersource` being set to `software` anywhere. I'm pretty sure we're able to capture an image with the Hamamatsu camera though. Is this issue redundant now?

**Comment by omarjamil** [comment]
The camera is by default goes into `internal` mode which is used for live imaging. The camera needs to be put into `internal` mode after it has been put in a different mode.

**Comment by felicityguest** [comment]
Closing this as the `Live` button is functional.
