### ISSUE TITLE
Select ROIs in GUI

### ISSUE THREAD

**Issue by jpallen** [UniExeterRSE/NetClamp#18]
Be able to select ROIs on an overlay on top of the image from the camera.

## Implementation Details

* Use `<canvas>` element on top of image display
* Be able to select circles or min/max bounding box
* Sync to backend when you click 'save', and reload ROIs to front-end on page refresh
* Give each ROI and unique id to refer to it (and match to timeseries in future)
* Make sure data structures/variables/classes etc capture the type of shape, so that we can extend with new shapes in future (e.g. rect, circle, polygon path)

## Acceptance Criteria

- [ ] ROIs are selectable in front-end, either as circle or rectangle
- [ ] ROIs are persisted on back-end (in memory for now), so persist on page refresh

**Comment by omarjamil** [comment]
Implemented in client.js
