### ISSUE TITLE
Store ROIs on disk

### ISSUE THREAD

**Issue by jpallen** [UniExeterRSE/NetClamp#19]
Storage to hard disk of these ROIs via coordinates commensurate via the DMS system (compatible with the projector)

**Comment by omarjamil** [comment]
ROIs are likely to bit strings (5 bits) and order in the list will be the label. This can be saved in a simple text file.

**Comment by omarjamil** [comment]
@felicityguest You might have this plan already, but thought it is worth considering using `SessionInfo` in `netclamp` to pass the ROI information to the server first. Then the server can save it and/or use it for processing.

**Comment by felicityguest** [comment]
Completed as part of #121.
