### ISSUE TITLE
Turn ROIs and images into df/F time series

### ISSUE THREAD

**Issue by jpallen** [UniExeterRSE/NetClamp#56]
This capture the image processing side of things, not plotting in the GUI. Apply thresholding calculation to each of the ROIs to every frame. This will be the time series.

**Comment by omarjamil** [comment]
ROIs are currently averaging. Need to check the correct thresolding for the expriment.

**Comment by stephenpcook** [comment]
The timeseries is `(roi.history - roi_ref) / roi_ref`, and `roi_ref` is currently set as `roi.history[0]` (as added by #125).

**Comment by stephenpcook** [comment]
`roi_ref` set to `roi.ref_value` in #130.
