### ISSUE TITLE
Change GitHub actions OS to Windows Server

### ISSUE THREAD

**Issue by mtwest2718** [UniExeterRSE/NetClamp#58]
Because the main application will be running on a Windows box with compiled C++ drivers for Windows, I feel like we shouldn't be using an Ubuntu instance for CI/CD testing. At the least the `hamamatsu.dcam` driver wrapper API will be installed properly and those import statements won't fail automated testing.

This change shouldn't effect any of the webcam related development.

**Comment by omarjamil** [comment]
CI on MacOS, Linux, Windows.
