### ISSUE TITLE
Implement a RESTful API

### ISSUE THREAD

**Issue by FreddyWordingham** [UniExeterRSE/NetClamp#77]
At the moment the routing framework is a bit slap dash.
Better practice would be to maintain a RESTful API as described [here](https://flask-restful.readthedocs.io/en/latest/).

This will require a slight refactor to the application code (note nothing needs to change in the main library code)- but it would be better to implement this sooner rather than later, so I'm going to practice RESTful in playgound repo/branch, and then will focus on this for my next PR.

**Comment by omarjamil** [comment]
Enhancement, but not necessary.
