### ISSUE TITLE
Add app stages

### ISSUE THREAD

**Issue by FreddyWordingham** [UniExeterRSE/NetClamp#82]
Add 'stages' to the app:
- Setup (general settings)
  - Select camera
- Config (camera specific settings)
  - Resolution
  - Gain
  - Exposure time / FPS
  - Display FPS
  - Threshold
  - etc...
- Calibration (ROI filters)
  - Set ROI
- Experiment (run)
  - Running plot of ROI totals/averages
- Analysis
  - Total Plot
  - Save

**Comment by omarjamil** [comment]
Closing this and will create smaller task issues. The project management can be done via the project board.
